# Generated by Django 4.2.7 on 2024-05-04 09:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('depertment', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(default='', max_length=100)),
                ('registration_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], default='student', max_length=10)),
            ],
            options={
                'db_table': 'User_infoo',
            },
        ),
        migrations.CreateModel(
            name='Counselling_Hour',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('weekday', models.CharField(choices=[('saturday', 'Saturday'), ('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday')], default='saturday', max_length=10)),
                ('slot1', models.BooleanField(default=False)),
                ('slot2', models.BooleanField(default=False)),
                ('slot3', models.BooleanField(default=False)),
                ('slot4', models.BooleanField(default=False)),
                ('slot5', models.BooleanField(default=False)),
                ('slot6', models.BooleanField(default=False)),
                ('slot7', models.BooleanField(default=False)),
                ('slot8', models.BooleanField(default=False)),
                ('on', models.BooleanField(default=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='main_app.user', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('massage_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=100)),
                ('massage', models.CharField(max_length=100)),
                ('weekday', models.CharField(choices=[('saturday', 'Saturday'), ('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday')], default='saturday', max_length=10)),
                ('slot', models.CharField(choices=[('08:30 AM', '08:30 AM'), ('09:45 AM', '09:45 AM'), ('11:00 AM', '11:00 AM'), ('12:15 PM', '12:15 PM'), ('01:30 PM', '01:30 PM'), ('02:45 PM', '02:45 PM'), ('04:00 PM', '04:00 PM'), ('05:15 PM', '05:15 PM')], default='08:30 AM', max_length=10)),
                ('approve', models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('booking_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_id', to='main_app.user', verbose_name='')),
            ],
        ),
    ]
